name: Contributor CI Build ğŸ—ï¸
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release' ) && format('contributor-pr-base-{0}', github.sha) || format('contributor-pr-{0}', github.ref) }}
  cancel-in-progress: false
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
permissions: {}
jobs:
  build:
    name: Compile All ğŸ“¦
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository ğŸ“¥
        uses: actions/checkout@v6
      - name: Setup Test Matrix
        id: setup-matrix
        run: echo "matrix=$(jq -c -f .github/workflows/extract-unit-test-split.jq .teamcity/subprojects.json)" >> $GITHUB_OUTPUT
      - name: Setup Java â˜•ï¸ï¸
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Determine System Properties
        id: determine-sys-prop-args
        uses: actions/github-script@v8
        with:
          script: |
            if (context.payload.pull_request && context.payload.pull_request.head.repo.fork) {
                core.setOutput('sys-prop-args', '-DagreePublicBuildScanTermOfService=yes -Ddevelocity.edge.discovery=false -DcacheNode=us --scan')
            } else {
                core.setOutput('sys-prop-args', '')
            }
      - name: Setup Gradle ğŸ˜
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
      - name: Compile All Code ğŸ”¨
        run: ./gradlew compileAll -DdisableLocalCache=true ${{ steps.determine-sys-prop-args.outputs.sys-prop-args }}
      - name: Upload Build Receipt ğŸ“„
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: build-receipt.properties
          path: platforms/core-runtime/base-services/build/generated-resources/build-receipt/org/gradle/build-receipt.properties
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
      sys-prop-args: ${{ steps.determine-sys-prop-args.outputs.sys-prop-args }}
  sanity-check:
    name: Sanity Check on Linux âœ…
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository ğŸ“¥
        uses: actions/checkout@v6
      - name: Setup Java â˜•ï¸
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Download Build Receipt ğŸ“¥
        uses: actions/download-artifact@v6
        with:
          name: build-receipt.properties
          path: incoming-distributions/build-receipt.properties
      - name: Setup Gradle ğŸ˜
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
      - name: Sanity Check ğŸ§ª
        run: ./gradlew sanityCheck -DdisableLocalCache=true ${{ needs.build.outputs.sys-prop-args }}
      - name: Sanity Check - Rewrite âš™ï¸
        run: ./gradlew rewriteDryRun -DdisableLocalCache=true ${{ needs.build.outputs.sys-prop-args }} -Dorg.gradle.jvmargs=-Xmx4G
      - name: Upload Compatibility Report ğŸ“Š
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: binary-compatibility-report
          path: testing/architecture-test/build/reports/binary-compatibility/report.html
  unit-test:
    name: ${{ matrix.bucket.name }} - (Unit Test) ğŸ§ª
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        bucket: ${{ fromJson(needs.build.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout Repository ğŸ“¥
        uses: actions/checkout@v6
      - name: Setup Java â˜•ï¸
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Download Build Receipt ğŸ“¥
        uses: actions/download-artifact@v6
        with:
          name: build-receipt.properties
          path: incoming-distributions/build-receipt.properties
      - name: Setup Gradle ğŸ˜
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
      - name: Run Unit Tests ğŸ§ª
        run: ./gradlew ${{ matrix.bucket.tasks }} -DdisableLocalCache=true -PflakyTests=exclude ${{ needs.build.outputs.sys-prop-args }}
  unit-test-windows-arm:
    name: Unit Test Windows ARM ğŸªŸ
    permissions:
      contents: read
    runs-on: windows-11-arm
    needs: build
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout Repository ğŸ“¥
        uses: actions/checkout@v6
      - name: Setup Java â˜•ï¸
        uses: actions/setup-java@v5
        with:
          distribution: microsoft
          java-version: 17
      - name: Download Build Receipt ğŸ“¥
        uses: actions/download-artifact@v6
        with:
          name: build-receipt.properties
          path: incoming-distributions/build-receipt.properties
      - name: Setup Gradle ğŸ˜
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
      - name: Run Native Tests ğŸ§ª
        run: ./gradlew :native:test --% -DdisableLocalCache=true -PflakyTests=exclude ${{ needs.build.outputs.sys-prop-args }}
